// <auto-generated />
using System;
using MVC_Crud.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Crud.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241030124553_SeedDataUpload")]
    partial class SeedDataUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Crud.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");

                    b.HasData(
                        new
                        {
                            MusteriId = 1,
                            Ad = "Ali",
                            Email = "ali.yilmaz@example.com",
                            Soyad = "Yılmaz"
                        },
                        new
                        {
                            MusteriId = 2,
                            Ad = "Ayşe",
                            Email = "ayse.kara@example.com",
                            Soyad = "Kara"
                        },
                        new
                        {
                            MusteriId = 3,
                            Ad = "Mehmet",
                            Email = "mehmet.demir@example.com",
                            Soyad = "Demir"
                        },
                        new
                        {
                            MusteriId = 4,
                            Ad = "Fatma",
                            Email = "fatma.ozturk@example.com",
                            Soyad = "Öztürk"
                        },
                        new
                        {
                            MusteriId = 5,
                            Ad = "Hasan",
                            Email = "hasan.celik@example.com",
                            Soyad = "Çelik"
                        },
                        new
                        {
                            MusteriId = 6,
                            Ad = "Zeynep",
                            Email = "zeynep.koc@example.com",
                            Soyad = "Koç"
                        },
                        new
                        {
                            MusteriId = 7,
                            Ad = "Emre",
                            Email = "emre.aydin@example.com",
                            Soyad = "Aydın"
                        },
                        new
                        {
                            MusteriId = 8,
                            Ad = "Seda",
                            Email = "seda.akman@example.com",
                            Soyad = "Akman"
                        },
                        new
                        {
                            MusteriId = 9,
                            Ad = "Burak",
                            Email = "burak.sonmez@example.com",
                            Soyad = "Sönmez"
                        },
                        new
                        {
                            MusteriId = 10,
                            Ad = "Elif",
                            Email = "elif.yavuz@example.com",
                            Soyad = "Yavuz"
                        });
                });

            modelBuilder.Entity("MVC_Crud.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SiparisId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("UrunId");

                    b.ToTable("Siparisler");

                    b.HasData(
                        new
                        {
                            SiparisId = 1,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4916),
                            UrunId = 1
                        },
                        new
                        {
                            SiparisId = 2,
                            MusteriId = 1,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4934),
                            UrunId = 2
                        },
                        new
                        {
                            SiparisId = 3,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4936),
                            UrunId = 3
                        },
                        new
                        {
                            SiparisId = 4,
                            MusteriId = 2,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4938),
                            UrunId = 4
                        },
                        new
                        {
                            SiparisId = 5,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4940),
                            UrunId = 5
                        },
                        new
                        {
                            SiparisId = 6,
                            MusteriId = 3,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4942),
                            UrunId = 6
                        },
                        new
                        {
                            SiparisId = 7,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(4943),
                            UrunId = 7
                        },
                        new
                        {
                            SiparisId = 8,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5001),
                            UrunId = 8
                        },
                        new
                        {
                            SiparisId = 9,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5004),
                            UrunId = 9
                        },
                        new
                        {
                            SiparisId = 10,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5006),
                            UrunId = 10
                        },
                        new
                        {
                            SiparisId = 11,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5008),
                            UrunId = 1
                        },
                        new
                        {
                            SiparisId = 12,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5011),
                            UrunId = 2
                        },
                        new
                        {
                            SiparisId = 13,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5013),
                            UrunId = 3
                        },
                        new
                        {
                            SiparisId = 14,
                            MusteriId = 4,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5015),
                            UrunId = 5
                        },
                        new
                        {
                            SiparisId = 15,
                            MusteriId = 5,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5017),
                            UrunId = 6
                        },
                        new
                        {
                            SiparisId = 16,
                            MusteriId = 6,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5020),
                            UrunId = 7
                        },
                        new
                        {
                            SiparisId = 17,
                            MusteriId = 7,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5022),
                            UrunId = 8
                        },
                        new
                        {
                            SiparisId = 18,
                            MusteriId = 8,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5023),
                            UrunId = 9
                        },
                        new
                        {
                            SiparisId = 19,
                            MusteriId = 9,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5025),
                            UrunId = 10
                        },
                        new
                        {
                            SiparisId = 20,
                            MusteriId = 10,
                            SiparisTarihi = new DateTime(2024, 10, 30, 15, 45, 50, 909, DateTimeKind.Local).AddTicks(5027),
                            UrunId = 1
                        });
                });

            modelBuilder.Entity("MVC_Crud.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunId = 1,
                            Adi = "Laptop",
                            Fiyat = 2500m
                        },
                        new
                        {
                            UrunId = 2,
                            Adi = "Akıllı Telefon",
                            Fiyat = 1500m
                        },
                        new
                        {
                            UrunId = 3,
                            Adi = "Tablet",
                            Fiyat = 1200m
                        },
                        new
                        {
                            UrunId = 4,
                            Adi = "Kulaklık",
                            Fiyat = 300m
                        },
                        new
                        {
                            UrunId = 5,
                            Adi = "Masaüstü Bilgisayar",
                            Fiyat = 2000m
                        },
                        new
                        {
                            UrunId = 6,
                            Adi = "Monitör",
                            Fiyat = 800m
                        },
                        new
                        {
                            UrunId = 7,
                            Adi = "Klavyeli",
                            Fiyat = 400m
                        },
                        new
                        {
                            UrunId = 8,
                            Adi = "Yazıcı",
                            Fiyat = 600m
                        },
                        new
                        {
                            UrunId = 9,
                            Adi = "Modem",
                            Fiyat = 250m
                        },
                        new
                        {
                            UrunId = 10,
                            Adi = "Harici Disk",
                            Fiyat = 500m
                        });
                });

            modelBuilder.Entity("MVC_Crud.Models.Siparis", b =>
                {
                    b.HasOne("MVC_Crud.Models.Musteri", "Musteri")
                        .WithMany("Siparis")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Crud.Models.Urun", "Urun")
                        .WithMany("Siparisler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MVC_Crud.Models.Musteri", b =>
                {
                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("MVC_Crud.Models.Urun", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
